### ISSUE TITLE
Filter the submenu

### ISSUE THREAD

**Issue by tonytamsf** [tonytamsf/Android-chefmenu#11]
Right now all the menu is shown for every subsection, obviously not good

**Comment by tonytamsf** [comment]
able to filter now
https://github.com/tonytamsf/Android-chefmenu/commit/74cd1e0d1f9f35256b8f9aa26929a62cfcb89f50

But still 2 bugs
1) empty tab at the end
2) the first tab is empty until I swipe to the right twice and swipe back (the loading tab is the submenu)

this code is all wrong
https://github.com/tonytamsf/Android-chefmenu/blob/74cd1e0d1f9f35256b8f9aa26929a62cfcb89f50/chefsmenu/src/main/java/com/wordpress/tonytam/chefsmenu/ChefMenuActivity.java#L108

**Comment by tonytamsf** [comment]
04-05 08:30:47.337    2042-2042/com.wordpress.tonytam.chefsmenu E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.wordpress.tonytam.chefsmenu, PID: 2042
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wordpress.tonytam.chefsmenu/com.wordpress.tonytam.chefsmenu.ChefMenuActivity}: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at com.wordpress.tonytam.chefsmenu.ChefMenuActivity$SectionsPagerAdapter$1.onDataReady(ChefMenuActivity.java:109)
            at com.wordpress.tonytam.chefsmenu.MenuRestClientUse.readOffineData(MenuRestClientUse.java:230)
            at com.wordpress.tonytam.chefsmenu.MenuRestClientUse.fetchMenuItems(MenuRestClientUse.java:59)
            at com.wordpress.tonytam.chefsmenu.ChefMenuActivity$SectionsPagerAdapter.<init>(ChefMenuActivity.java:102)
            at com.wordpress.tonytam.chefsmenu.ChefMenuActivity.onCreate(ChefMenuActivity.java:52)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
