### ISSUE TITLE
handle network failures: onFailure(int, Header[], Throwable, JSONObject) was not overriden, but callback was received

### ISSUE THREAD

**Issue by tonytamsf** [tonytamsf/Android-chefmenu#3]
03-23 09:10:26.541  18834-18834/com.wordpress.tonytam.chefsmenu W/JsonHttpResponseHandler﹕ onFailure(int, Header[], Throwable, JSONObject) was not overriden, but callback was received
    org.apache.http.client.HttpResponseException: OK
            at com.loopj.android.http.AsyncHttpResponseHandler.sendResponseMessage(AsyncHttpResponseHandler.java:404)
            at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:161)
            at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
            at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
03-23 09:10:26.541  18834-18834/com.wordpress.tonytam.chefsmenu W/JsonHttpResponseHandler﹕ onFailure(int, Header[], Throwable, JSONObject) was not overriden, but callback was received
    org.apache.http.client.HttpResponseException: OK
            at com.loopj.android.http.AsyncHttpResponseHandler.sendResponseMessage(AsyncHttpResponseHandler.java:404)
            at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:161)
            at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
            at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
03-23 09:10:26.551  18834-18834/com.wordpress.tonytam.chefsmenu W/JsonHttpResponseHandler﹕ onFailure(int, Header[], Throwable, JSONObject) was not overriden, but callback was received
    org.apache.http.client.HttpResponseException: OK
            at com.loopj.android.http.AsyncHttpResponseHandler.sendResponseMessage(AsyncHttpResponseHandler.java:404)
            at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:161)
            at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
            at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
03-23 09:10:26.551  18834-18834/com.wordpress.tonytam.chefsmenu W/JsonHttpResponseHandler﹕ onFailure(int, Header[], Throwable, JSONObject) was not overriden, but callback was received
    org.apache.http.client.HttpResponseException: OK
            at com.loopj.android.http.AsyncHttpResponseHandler.sendResponseMessage(AsyncHttpResponseHandler.java:404)
            at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:161)
            at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
            at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by tonytamsf** [comment]
api response

```
03-23 09:16:14.470  19690-19690/com.wordpress.tonytam.chefsmenu W/System.err﹕ onFailure: {"error":"You have exceeded your API access limit. Please try again later, or contact support@locu.com to request an increase your limit.","http_status":429,"status":"error"}
```
