### ISSUE TITLE
Selecting a submenu greater than 3, getting exception.

### ISSUE THREAD

**Issue by tonytamsf** [tonytamsf/Android-chefmenu#5]
Don't hardcode

```
03-23 10:37:37.176    2884-2884/com.wordpress.tonytam.chefsmenu E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.wordpress.tonytam.chefsmenu, PID: 2884
    java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at com.wordpress.tonytam.chefsmenu.SubMenuFragment.onItemClick(SubMenuFragment.java:166)
            at android.widget.AdapterView.performItemClick(AdapterView.java:300)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044)
            at android.widget.AbsListView$3.run(AbsListView.java:3833)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by tonytamsf** [comment]
fixed https://github.com/tonytamsf/Android-chefmenu/commit/c717f2f139bf1202092d206e03d5ebd3b08c7b3a
