### ISSUE TITLE
Handle basic networking failures

### ISSUE THREAD

**Issue by tonytamsf** [tonytamsf/Android-chefmenu#7]
If a device is completely offline, may as well check for network first and do something smart

```03-24 08:53:19.789    2802-2802/com.wordpress.tonytam.chefsmenu V/JsonHttpResponseHandler﹕ response body is null, calling onFailure(Throwable, JSONObject)
03-24 08:53:19.800    2802-2802/com.wordpress.tonytam.chefsmenu W/JsonHttpResponseHandler﹕ onFailure(int, Header[], Throwable, JSONObject) was not overriden, but callback was received
    java.io.IOException: UnknownHostException exception: Unable to resolve host "dl.dropboxusercontent.com": No address associated with hostname
            at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:184)
            at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
03-24 08:53:19.800    2802-2802/com.wordpress.tonytam.chefsmenu W/System.err﹕ onFailure: null
03-24 08:53:19.865    2802-2820/com.wordpress.tonytam.chefsmenu W/EGL_emulation﹕ eglSurfaceAttrib not implemented
03-24 08:53:19.865    2802-2820/com.wordpress.tonytam.chefsmenu W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa58f9840, error=EGL_SUCCESS

```
```

**Comment by tonytamsf** [comment]
fixed https://github.com/tonytamsf/Android-chefmenu/commit/c717f2f139bf1202092d206e03d5ebd3b08c7b3a
